site_name: Jsonline
repo_name: 'fsadannn/jsonline'
repo_url: 'https://github.com/fsadannn/jsonline'

theme:
    name: material
    feature:
        tabs: true

markdown_extensions:
    - codehilite
    - toc:
        permalink: true
    - admonition

nav:
    - Home: index.md
