name: Python Package

on:
  push:
    tags:
      - 'v*'


jobs:
  build-n-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: testing
      run: ls -la

    - name: Verify tag is on master branch
      run: |
        if ! git branch -r --contains ${{ github.ref_name }} | grep -q 'origin/master'; then
          echo "Tag ${{ github.ref_name }} is not on the master branch."
          exit 1
        fi

    - uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml' # Read python version from a file pyproject.toml

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Install the project
      run: uv sync --locked --all-extras --dev --no-install-project

    - name: Build package
      run: uv build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
